name: File Operations

on:
  workflow_dispatch:

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5


      - name: Show file content
        run: cat .github/workflows/demo.txt


      - name: List directory
        run: ls -l

      - name: Execute shell script
        run: chmod +x .github/workflows/uptime.sh

