name: File Operations

on: push

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "KK FUNDA TEST FILE" > demo.txt

      - name: Show file content
        run: cat demo.txt

      - name: List directory
        run: ls -l
